//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccesosWS
    {
        public int id { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> fec_alta { get; set; }
        public Nullable<int> reg_alta { get; set; }
        public Nullable<System.DateTime> fec_baja { get; set; }
        public Nullable<int> reg_baja { get; set; }
        public Nullable<int> id_status { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
