//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREMARK_PLANPISO_AML
    {
        public int Id_RemarkPlan { get; set; }
        public Nullable<int> Dealer { get; set; }
        public string RazonSocial { get; set; }
        public string FechaContitucion { get; set; }
        public string RFC { get; set; }
        public string Nacionalidad { get; set; }
        public string GiroMercantil { get; set; }
        public string Nombre { get; set; }
        public string Ap_Paterno { get; set; }
        public string Ap_Materno { get; set; }
        public string FechaNacimiento { get; set; }
        public string RFC1 { get; set; }
        public string Curp { get; set; }
        public Nullable<int> CP { get; set; }
        public string Estado { get; set; }
        public string Municipio { get; set; }
        public string Colonia { get; set; }
        public string Calle { get; set; }
        public string N_Exterior { get; set; }
        public string N_Interior { get; set; }
        public string N_Telefono { get; set; }
        public string Correo { get; set; }
        public string Vin { get; set; }
        public string FechaDisposicion { get; set; }
        public Nullable<decimal> MontoOperacion { get; set; }
        public string Fecha_creacion { get; set; }
        public string Users { get; set; }
        public string Remarketing_Plan { get; set; }
    }
}
