//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KBITACORA_AML
    {
        public int BIT_FL_CVE { get; set; }
        public System.DateTime BIT_FE_FECHA { get; set; }
        public int PRM_FL_CVE { get; set; }
        public string BIT_DS_DESCRIPCION { get; set; }
        public string BIT_DS_RESUMEN { get; set; }
        public string USR_CL_CVE { get; set; }
    }
}
