//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KCONFIG_AML
    {
        public int AML_ID_CVE { get; set; }
        public Nullable<int> PAR_CL_VALOR { get; set; }
        public string AML_DS_DES { get; set; }
        public Nullable<decimal> AML_NO_MONTO { get; set; }
        public string AML_DS_EMAIL { get; set; }
        public Nullable<int> AML_FG_STATUS { get; set; }
        public string USR_CL_CVEALTA { get; set; }
        public Nullable<System.DateTime> AML_FE_ALTA { get; set; }
        public string USR_CL_CVEMOD { get; set; }
        public Nullable<System.DateTime> AML_FE_MOD { get; set; }
    }
}
