//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosRoles
    {
        public int Id { get; set; }
        public int IdMenu { get; set; }
        public int IdRole { get; set; }
        public bool Activo { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual Permisos Permisos { get; set; }
    }
}
