//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permisos()
        {
            this.Permisos1 = new HashSet<Permisos>();
            this.PermisosRoles = new HashSet<PermisosRoles>();
            this.Asignacion_Modulos = new HashSet<Asignacion_Modulos>();
        }
    
        public int IdMenu { get; set; }
        public int IdModulo { get; set; }
        public string Accion { get; set; }
        public string Controlador { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool EsMenu { get; set; }
        public bool Activo { get; set; }
        public Nullable<byte> Nivel { get; set; }
        public Nullable<int> IdPadre { get; set; }
        public bool AllUsers { get; set; }
        public string Icon { get; set; }
    
        public virtual Modulos Modulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permisos> Permisos1 { get; set; }
        public virtual Permisos Permisos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermisosRoles> PermisosRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignacion_Modulos> Asignacion_Modulos { get; set; }
    }
}
